### ISSUE TITLE
Player facing wrong direction in inventory while sitting

### ISSUE THREAD

**Issue by Jayjoe4** [Modflower/polysit#1]
### Environment

- **Minecraft**:
- **Polysit**:
- **Polymer**:
- **Loader**:
- **Java**:

### To reproduce

1. When sitting on a stair or slab opening the menu the player is facing west.

### Expected results

Fix this by opening inventory and player is facing towards you. 

### Actual results

Player facing west.

### Anything else?

<img width="571" alt="Captura de pantalla 2022-07-13 083529" src="https://user-images.githubusercontent.com/85653481/178746639-64974488-5a53-4e9b-b30a-207e9d6cdae4.png">
![2022-07-13_08 35 59](https://user-images.githubusercontent.com/85653481/178746772-bf2e2078-f4ac-4050-9f8c-d759c97b05e6.png)

**Comment by KJP12** [comment]
Testing on 1.18.2 and 1.19 with Quilt, it seems to be a vanilla bug dependent on which direction the living entity below you is facing, and it happens to be that the underlying seat / armor stand entity turns to always face where the player is facing. Riding pigs produce the same behaviour.

This may not be fixable purely on the server, and probably would be best left to <https://bugs.mojang.com>.

**Comment by Ampflower** [comment]
As it wouldn't be possible to fix this without hacking into the rendering code, I'll have to consider this a won't-fix.

I may consider making a mod that can fix it client-side if there isn't already one available tho.
