### ISSUE TITLE
Trying to use the latest version of Polysit on a 1.20.4 server with Via* mods installed causes 1.20.2 clients to be unable to join.

### ISSUE THREAD

**Issue by ArkoSammy12** [Modflower/polysit#7]
### Environment

- **Minecraft**: 1.20.4 Fabric server
- **Polysit**: `polysit-0.5.3+mc.1.20.1.jar`
- **Polymer**: `polymer-bundled-0.7.5+1.20.4.jar`
- **Loader**: Fabric Loader 0.15.6
- **Java**: Adoptium JDK 17

### To reproduce

1. Create and start a Fabric server with Fabric API, Polymer, PolySit, ViaVersion, ViaFabric and ViaBackwards.
2. Launch a 1.20.2 client.
3. Try to join server with 1.20.2 client.

### Expected results

Being able to join the 1.20.4 server with a 1.20.2 client

### Actual results

The 1.20.2 client cannot join the 1.20.4 server

### Anything else?

The client will be met with the following image 

![image](https://github.com/Modflower/polysit/assets/121594394/d366ad1c-1b9a-43de-9f43-9936e6a380e4)

The logs in the client are be the following:

https://mclo.gs/3cifKtI

Strangely enough, this issue doesn't happen with 1.20.1 clients and below. This problem goes away when I remove Polysit from the server's mods, so I imagine that Polysit is having some get-along issues with the Via* mods. However the issue could go beyond just Polysit. This could also be an issue with Polymer itself xd.

**Comment by Ampflower** [comment]
Likely a Polymer or Fabric API bug; it's failing on 1.20.4's experimental mobs, which aren't present in 1.20.2 and older.

**Comment by Ampflower** [comment]
Very likely Polymer's bug, reproduced with Fabric API + ViaFabric + Polymer + Polyfactory.

**Comment by ArkoSammy12** [comment]
I see. I guess the usage of PolySit triggers something in Polymer causing the issue to happen. I'm gonna close this issue now

**Comment by Ampflower** [comment]
So we don't duplicate work; am opening an issue there.

**Comment by ArkoSammy12** [comment]
> So we don't duplicate work; am opening an issue there.

Thank you 👍🏻
